d = {'num_rows': 10000000,
     'num_columns': 16,
     'duplicate_rows': {'count': 0, 'percentage': 0.0},
     'columns': {'link_service_sid': {'dtype': 'String',
                                      'null_count': 0,
                                      'unique_count': 10000000,
                                      'problematic_symbols': 0,
                                      'leading_gaps': 0,
                                      'str_empty_words': 0,
                                      'mixed_language': 0,
                                      'min_length': 10,
                                      'max_length': 10,
                                      'median_len': 10.0},
                 'epk_id': {'dtype': 'String',
                            'null_count': 3105,
                            'unique_count': 9579442,
                            'problematic_symbols': 0,
                            'leading_gaps': 0,
                            'str_empty_words': 0,
                            'mixed_language': 0,
                            'min_length': 19,
                            'max_length': 19,
                            'median_len': 19.0},
                 'mbk_full_notification_flag': {'dtype': 'Int32',
                                                'null_count': 0,
                                                'unique_count': 2,
                                                'min': 0,
                                                'max': 1,
                                                'zero_count': 3409083,
                                                'quantile': {'lower_bound': -3.0,
                                                             'lower_count': 0,
                                                             'upper_bound': 4.0,
                                                             'upper_count': 0}},
                 'card_sid': {'dtype': 'String',
                              'null_count': 0,
                              'unique_count': 9996522,
                              'problematic_symbols': 0,
                              'leading_gaps': 0,
                              'str_empty_words': 0,
                              'mixed_language': 0,
                              'min_length': 2,
                              'max_length': 9,
                              'median_len': 9.0},
                 'card_dpan_num': {'dtype': 'String',
                                   'null_count': 105,
                                   'unique_count': 9961956,
                                   'problematic_symbols': 0,
                                   'leading_gaps': 0,
                                   'str_empty_words': 0,
                                   'mixed_language': 0,
                                   'min_length': 16,
                                   'max_length': 18,
                                   'median_len': 16.0},
                 'phone_sid': {'dtype': 'String',
                               'null_count': 0,
                               'unique_count': 9653031,
                               'problematic_symbols': 0,
                               'leading_gaps': 0,
                               'str_empty_words': 0,
                               'mixed_language': 0,
                               'min_length': 4,
                               'max_length': 10,
                               'median_len': 9.0},
                 'phone_num': {'dtype': 'String',
                               'null_count': 358,
                               'unique_count': 9622444,
                               'problematic_symbols': 0,
                               'leading_gaps': 0,
                               'str_empty_words': 0,
                               'mixed_language': 0,
                               'min_length': 11,
                               'max_length': 11,
                               'median_len': 11.0},
                 'mbk_blocked_flag': {'dtype': 'Int32',
                                      'null_count': 0,
                                      'unique_count': 2,
                                      'min': 0,
                                      'max': 1,
                                      'zero_count': 9339266,
                                      'quantile': {'lower_bound': 0.0,
                                                   'lower_count': 0,
                                                   'upper_bound': 0.0,
                                                   'upper_count': 660734}},
                 'update_channel_code': {'dtype': 'String',
                                         'null_count': 0,
                                         'unique_count': 6,
                                         'problematic_symbols': 0,
                                         'leading_gaps': 0,
                                         'str_empty_words': 0,
                                         'mixed_language': 0,
                                         'min_length': 1,
                                         'max_length': 1,
                                         'median_len': 1.0},
                 'is_deleted_flag': {'dtype': 'Int32',
                                     'null_count': 0,
                                     'unique_count': 2,
                                     'min': 0,
                                     'max': 1,
                                     'zero_count': 8869152,
                                     'quantile': {'lower_bound': 0.0,
                                                  'lower_count': 0,
                                                  'upper_bound': 0.0,
                                                  'upper_count': 1130848}},
                 'start_dttm': {'dtype': "Datetime(time_unit='ns', time_zone=None)",
                                'null_count': 0,
                                'unique_count': 8439793,
                                'less_min_date': 0,
                                'more_cur_date': 0,
                                'default_1970_count': 0,
                                'min_date': '2020-08-24',
                                'max_date': '2026-04-12'},
                 'end_dttm': {'dtype': "Datetime(time_unit='ns', time_zone=None)",
                              'null_count': 0,
                              'unique_count': 1,
                              'less_min_date': 10000000,
                              'more_cur_date': 0,
                              'default_1970_count': 0,
                              'min_date': '1816-03-29',
                              'max_date': '1816-03-29'},
                 'row_hash': {'dtype': 'String',
                              'null_count': 0,
                              'unique_count': 10000000,
                              'problematic_symbols': 0,
                              'leading_gaps': 0,
                              'str_empty_words': 0,
                              'mixed_language': 0,
                              'min_length': 64,
                              'max_length': 64,
                              'median_len': 64.0},
                 'ctl_action': {'dtype': 'String',
                                'null_count': 0,
                                'unique_count': 1,
                                'problematic_symbols': 0,
                                'leading_gaps': 0,
                                'str_empty_words': 0,
                                'mixed_language': 0,
                                'min_length': 1,
                                'max_length': 1,
                                'median_len': 1.0},
                 'ctl_loading': {'dtype': 'Int64',
                                 'null_count': 0,
                                 'unique_count': 152,
                                 'min': 145334408,
                                 'max': 162354555,
                                 'zero_count': 0,
                                 'quantile': {'lower_bound': 145334408.0,
                                              'lower_count': 0,
                                              'upper_bound': 145334408.0,
                                              'upper_count': 2433694}},
                 'ctl_validfrom': {'dtype': "Datetime(time_unit='ns', time_zone=None)",
                                   'null_count': 0,
                                   'unique_count': 152,
                                   'less_min_date': 0,
                                   'more_cur_date': 0,
                                   'default_1970_count': 0,
                                   'min_date': '2025-11-14',
                                   'max_date': '2026-04-12'}},
     'column_groups': {'group_1': ['start_dttm',
                                   'end_dttm',
                                   'row_hash',
                                   'ctl_action',
                                   'ctl_loading',
                                   'ctl_validfrom',
                                   'part_1_month'],
                       'group_2': ['epk_id', 'phone_num'],
                       'group_3': [],
                       'group_4': ['link_service_sid',
                                   'mbk_full_notification_flag',
                                   'card_sid',
                                   'card_dpan_num',
                                   'phone_sid',
                                   'mbk_blocked_flag',
                                   'update_channel_code',
                                   'is_deleted_flag']},
     'cols_exist_null_partition': ['ctl_validfrom', 'ctl_loading'],
     'empty_partitions': 4,
     'meaningless_partitiions': None,
     'large_data_not_partitioned': [False, 3.493986490436576, 'ГБ'],
     'empty_description': None,
     'small_files': [False, 140.78663483286292, 'МБ'],
     'dataset_size': [422.77236534282565, 'ГБ'],
     'file_count': 3075,
     'dataset_row_count_estimation': 3230135916,
     'column_problem_flag': False}
